title: Hello, world! I'm Tome Kirov
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Tome Kirov
author-img: tome-kirov-1.png
about-author: I am a DevOps engineer focusing on the IaaC, pipelines and IoT. Always hungry to keep learning and share with you all. Future entrepreneurer.
social-github: kirovtome
social-linkedin: tomekirov
social-email: tomekirov@outlook.com

# Disqus
discus-identifier: kirovtome-blog # add your discus identifier
comments: true

# Tracker
analytics: UA-143963612-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
